export enum EPagesDataActionTypes {
  SET_NOW_PAGE_DATA = "SET_NOW_PAGE_DATA",
  SET_NOW_DATA_SUCCESS = "SET_NOW_DATA_SUCCESS",
  SET_NOW_DATA_ERROR = "SET_NOW_DATA_ERROR",
  UPDATE_NOW_DATE = "UPDATE_NOW_DATE",
  RESET = "RESET",
}
