#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn lint
yarn build

# if build is successful, then commit else abort commit

if [ $? -eq 0 ]; then
  echo "Build successful"
  exit 0
else
  echo "Build failed"
  exit 1
fi



